"""
lookups.py
-----------
All lookup tables (code -> text mapping) loaded as Python dicts.
These match the reference tables in your Supabase database.

Auto-generated from:
  - Personal_Info_Table.xlsx
  - Certificate_Table.xlsx
  - Experience_Table.xlsx

Format: each lookup is a dict { code(int): text(str) }
Use get_code(text, lookup) for text -> code reverse lookup with fuzzy matching.
"""

# ============================================================
# PERSONAL INFORMATION LOOKUPS
# ============================================================

RANK_LOOKUP = {
    1: "MASTER (Master)",
    2: "COFF (Chief Officer)",
    5: "4OFF (4th Officer)",
    10: "OS (Ordinary Seaman)",
    11: "DCAD (Cadet (Deck))",
    12: "CENG (Chief Engineer)",
    13: "2ENG (2nd Engineer)",
    14: "3ENG (3rd Engineer)",
    17: "ETO (Electroengineer)",
    19: "FITTER (Fitter)",
    20: "MMAN (Motorman)",
    21: "ECAD (Cadet (Engine))",
    22: "COOK (Cook)",
    23: "STW (Steward (ess))",
    24: "WELDER (Welder)",
    25: "OILER (Oiler)",
    26: "WIPER (Wiper)",
    28: "MESSM (Messman)",
    29: "Other (Other)",
    30: "MSI (Marine Superintendant)",
    39: "GP (General Purpose)",
    41: "ELEC (Electrician)",
    50: "FRMAN (Foreman)",
    51: "2OFF (2nd Officer)",
    52: "3OFF (3rd Officer)",
    53: "4ENG (4th Engineer)",
    54: "1ENG (1st Engineer)",
    58: "MECH (Mechanic)",
    59: "AB (Able Seaman)",
    60: "JENG (Junior Engineer)",
    67: "PMAN (Pumpman)",
    68: "ENG (Engineer)",
    69: "CHCOOK (Chief Cook)",
    72: "JOFF (Junior Officer)",
    75: "BOSUN (Bosun)",
    125: "MIGRATION-CHIEF ENGINEER BULK (CHIEF ENGINEER BULK)",
    133: "CE(MANT) (JEFE MANTENIMIENTO)",
    162: "MIGRATION-ARTISTA (ARTISTA)",
    166: "MIGRATION-OFF. STWD (OFF. STWD)",
    176: "MIGRATION-SKIPPER (SKIPPER)",
    177: "MIGRATION-MECAMAR (MECAMAR)",
    178: "MIGRATION-RECEPTION SUP (RECEPTION SUPERVISOR)",
    232: "MIGRATION-POTMAN (POTMAN)",
    240: "LIMPIADOR (LIMPIADOR)",
    241: "MIGRATION-PATRON PORTUARIO (PATRON PORTUARIO)",
    292: "MIGRATION- RSA (RETAIL SYSTEM ADMINISTRATOR)",
    314: "MIGRATION-AB/CR (AB/CRANE OPERATOR)",
    319: "MIGRATION-C/O/SDPO (C/O/SDPO)",
    321: "MIGRATION-2/O/JDPO (2/O/JDPO)",
    327: "MIGRATION-ENGINE CLEANER (ENGINE CLEANER)",
    500: "1AEA (1st Assist Engineer Officer (Trans)",
    501: "2/O/DPO (2off Dinamic Position)",
    502: "2COOK (2nd Cook )",
    503: "1AE (1st Assist Engineer)",
    504: "2AE (2nd Assist Engineer)",
    505: "3AE (3rd Assist Engineer)",
    506: "2OFS (2nd Officer Senior)",
    507: "ABCOOK (AB/Cook)",
    508: "ANI (Animador)",
    509: "APOF (Apprendice Barge Officer)",
    510: "AS/D (Assistant Driller)",
    511: "APE (Assistant Port Engineer)",
    512: "APB (Assistant Plumber)",
    513: "APAX (Auxiliar Pasaje)",
    514: "AHOST (Auxiliar Hosteleria)",
    515: "ACOOK (Assistant Cook)",
    516: "ACABIN (Assistant Cabin)",
    517: "B.UT (BAR UTILITY)",
    518: "B/WTR (BAR/WAITER)",
    519: "BBOY (BARBOY)",
    520: "B.OP (BARGE OPERATOR)",
    521: "BARM (BARMAN)",
    522: "BTND (BARTENDER)",
    523: "BWSS (BARWAITRESS)",
    524: "BSUP (BOARD SERVICES SUPERVISOR)",
    525: "BTOP (Boat Operator)",
    526: "BSNA (BOSUN A)",
    527: "BSNB (BOSUN B)",
    528: "BSNC (BOSUN C)",
    529: "BSND (BOSUN D)",
    530: "BSNE (BOSUN E)",
    531: "BTCHR (BUTCHER)",
    532: "COSD (1OFF Dinamic Position )",
    533: "CBOY (CABIN BOY)",
    534: "CGIRL (CABIN GIRL)",
    535: "CSTWD (CABIN STEWARD/ESS)",
    536: "CUTI (CABIN UTILITY)",
    537: "CSER (CAFE SERVER)",
    538: "CALD (CALDERETA)",
    539: "CALDN (CALDERETA NOCTURNO)",
    540: "CGEN (CARGO.ENG.)",
    541: "CRPT (CARPENTER)",
    542: "CASH (CASHIER)",
    543: "CASD (CASINO DEALER)",
    544: "CASM (CASINO MANAGER)",
    545: "C.STOR (CAT.STOREKEEPER)",
    546: "CATR (CATERING GIRL/BOY)",
    547: "CSPV (CATERING SUPERVISOR)",
    548: "CLED (CHEER LEADER DIRECTOR)",
    549: "ALIMP (Auxiliar Limpieza)",
    550: "CENGT (CHIEF ENGINEER TANKER)",
    551: "CE/1AE (CHIEF ENGINEER/1ST A. ENGINEER)",
    552: "COFFE (CHIEF OFFICER EUROPA)",
    553: "C.STWD (CHIEF STEWARD)",
    554: "2C.STWD (CHIEF STEWARD 2º ASSISTANT)",
    555: "ACSTWD (CHIEF STEWARD ASSISTANT)",
    558: "S.CLNR (CLEANER SUPERVISOR)",
    562: "R.COOK (COOK RESTAURANT)",
    563: "COOK/ST (COOK/STEWARD)",
    564: "CRNO (CRANE OPERATOR)",
    565: "DMAN (DANCER-MAN)",
    566: "DWMAN (DANCER-WOMAN)",
    567: "DBOY (DECK BOY)",
    569: "DECK FITTER (DECK FITTER)",
    572: "DHND (DECKHAND)",
    575: "DJ (DISK JOCKEY)",
    576: "DR (DOCTOR)",
    577: "DNK (DONKEYMAN)",
    587: "S.ETO (ETO Senior)",
    590: "F/MTM (FITTER/MOTORMAN)",
    591: "F/W (FITTER/WELDER)",
    592: "FMAN (FLOORMAN)",
    593: "FOODM (FOOD MANAGER)",
    594: "FORKD (FORKLIFT DRIVER)",
    595: "G/BOY (GALLEY BOY)",
    596: "G. UTI (GALLEY UTILITY)",
    597: "G.ENG (GAS ENGINEER)",
    598: "G.MEC (GAS MECHANIC)",
    599: "GVNS (GOVERNESS)",
    600: "GRS (GREASER)",
    601: "GUARDIAN (GUARDIAN)",
    602: "GUIT (GUITARRIST)",
    603: "HMAN (HANDYMAN)",
    604: "H.BART (HEAD BARTENDER)",
    605: "H.CLE (HEAD CLEANER)",
    606: "H.REC (HEAD RECEPCIONIST)",
    608: "H.WAIT (HEAD WAITER)",
    609: "HKCL (HK CLEANER)",
    611: "HTSS (HOSTESS)",
    612: "AHTSS (HOSTESS ASSISTANT)",
    613: "H.MAN (HOTEL MANAGER)",
    614: "H.S.ENG (HOTEL SERV ENGINEER)",
    616: "H.UT (HOTEL UTILITY)",
    617: "ILU (ILUSIONIST)",
    618: "J.CMA (JEFE DE CAMARA)",
    619: "JWRL (JEWELRY ATTENDANT)",
    620: "A.PURS (JUN. ASST.TRAINEE PURSER)",
    621: "J.ETO (JUNIOR ELECTRICIAN)",
    622: "K.UTI (KITCHEN UTILITY)",
    623: "A.GALLEY (KP/Galley Assistant)",
    624: "LUNDRY (LAUNDRY MAN/WOMAN)",
    625: "LBSN (LEADING BOSUN)",
    626: "LMTM (LIMITED MOTORMAN, CLASS A)",
    628: "LKEE (LINEN KEEPER)",
    629: "MAG (MAGICIAN)",
    630: "MTR (MAITRE)",
    633: "AB/MTM (MARINERO POLIVALENTE)",
    634: "MSSG (MASSAGER)",
    635: "M.BLK (MASTER BULK)",
    636: "M.TNK (MASTER TANKER)",
    637: "M-CO (MASTER-C/O)",
    638: "M-SDPO (MASTER/SDPO)",
    639: "MN2 (MEC.NAV. 2º)",
    640: "MNM (MEC.NAV.MAYOR)",
    642: "MMN (MECANICO MAYOR NAVAL)",
    643: "MN1 (MECANICO NAVAL PRIMERA)",
    644: "MED.O (MEDICAL OFFICER)",
    645: "2AMES (MESSMAN 2º ASSISTANT)",
    646: "AMESS (MESSMAN ASSISTANT)",
    648: "MUSIC (MUSICIAN)",
    649: "N.COOK (NIGHT COOK)",
    650: "N.STWD (NIGHT STEWARD)",
    651: "N.UTI (NIGHT UTILITY)",
    652: "NURSE (NURSE)",
    654: "O.MESS (OFF. MESSMAN)",
    656: "MTM/ETO (OILER/ELECTROMECHANIC)",
    657: "PTR (PAINTER)",
    658: "PANG (PANGUERO)",
    660: "BKR (PASTRY/BAKER)",
    661: "PATMAN (PATROLMAN)",
    662: "SKPR (PATRON)",
    664: "PIAN (PIANIST)",
    665: "PILT (PILOT)",
    666: "PLUM (PLUMBER)",
    667: "P.MST (PORT CAPTAIN)",
    669: "PPRR (PUBLIC RELATIONS)",
    670: "PSR (PURSER)",
    671: "J.RAD (RADIO OFFICER/JUNIOR)",
    672: "S.RAD (RADIO OFFICER/SENIOR)",
    673: "RECEPT (RECEPCIONIST)",
    675: "REDER (REDERO)",
    676: "A. REEFER (REEFER ASSIST.)",
    677: "ENG REEF (REEFER ENGINEER)",
    678: "RPMAN (REPAIR MAN)",
    680: "RIGME (RIG MECHANIC)",
    681: "RIG (RIGGER)",
    682: "RNECK (ROUGHNECK)",
    683: "RTBT (ROUSTABOUT)",
    684: "S.OFF (SAFETY OFFICER)",
    685: "2MEC (SECOND MECHANIC)",
    686: "2PLUMB (SECOND PLUMBER)",
    687: "2STWD (SECOND STEWARD)",
    688: "SECR (SECURITY)",
    689: "SER.U (SELF UTILITY SERVICE)",
    690: "SBSN (SENIOR BOSUN)",
    691: "S ELECT (SENIOR ELECTRICIAN)",
    692: "SFITT (SENIOR FITTER)",
    694: "SSO (SHIPBOARD SAFETY OFFICER)",
    695: "SHIP.FIT (SHIPFITTER)",
    696: "ASHOP (SHOP ASSISTANT)",
    697: "SHOPG (SHOP GIRL)",
    699: "SBFTT (SNACK BUFFET)",
    700: "SCARG (SOBRECARGO)",
    701: "S.RECEPT (SR. RECEPTIONIST)",
    702: "A.STWD (STEWARD ASSISTANT)",
    703: "A.STORE (STORE KEEPER ASSISTANT)",
    704: "S.STORE (STORE SUPERVISOR)",
    705: "STOREM (STOREMAN)",
    706: "SCARG/SUPERN (SUPERCARGO/SUPERNUMERARY)",
    707: "S.INTENT (SUPERINTENDENT)",
    708: "SUPERN (SUPERNUMERARY)",
    710: "S.CAT (SUPERVISOR CATERING)",
    711: "S.HOST (SUPERVISOR HOSTELERIA)",
    712: "S.LIMP (SUPERVISOR LIMPIEZA)",
    713: "S.RECEPT (SUPERVISOR RECEPCION)",
    714: "CLNTNK (TANK CLEANER)",
    715: "T. ENG (TECHNICAL ENGINEER)",
    716: "TUTOR (TUTOR)",
    717: "U.MTM (UNLIMITED MOTORMAN)",
    718: "U.MAN (UTILITY MAN)",
    719: "WTR (WAITER)",
    720: "YMAN (YEOMAN)",
    721: "ABOSN (ASSISTANT BOSUN)",
    722: "AB II/5 (ABLE SEAMAN DECK II/5)",
    723: "CLNR (Cleaner)",
    724: "RP.REST (RESPONSABLE RESTAURACION)",
    725: "RP.COOK (RESPONSABLE COCINA CORPORATIVA)",
    726: "CASD S. (CASINO DEALER SENIOR)",
    727: "ETR (Electro-technical Rating)",
    729: "Cust.Serv.Crew (Customer Service Crew)",
    730: "INSP (INSPECTOR)",
    731: "MST/1OFF (MASTER / 1OFF)",
    732: "OBS Spv. (OBS Supervisor)",
    733: "D.MAN (Duty Manager)",
    734: "ABJUN (AB JUNIOR)",
    735: "ENG FITTER (ENGINE FITTER)",
    736: "SOUS CHEF (SOUS CHEF)",
}

STATUS_LOOKUP = {
    4: "applicant",
    5: "pool seafarer",
    8: "NTBR (inactive)",
    10: "online applicant",
    11: "not available (inactive)",
}

CITIZENSHIP_LOOKUP = {
    1: "Citizen",
    2: "Alien",
    3: "Non citizen",
    4: "Stateless",
}

SALARY_CURRENCY_LOOKUP = {
    1: "USD",
    2: "EUR",
    3: "GBP",
    4: "BRL",
}

SALARY_TYPE_LOOKUP = {
    1: "daily",
    2: "monthly",
    3: "annually",
}

NOTICE_TYPE_LOOKUP = {
    1: "months",
    2: "weeks",
    3: "days",
}

# ============================================================
# CERTIFICATE LOOKUPS (grouped by category)
# ============================================================

CERT_TRAVEL_DOCUMENTS = {
    23: "Seaman's Book",
    105: "Passport",
    215: "Visa",
    241: "Residence permit",
    635: "ID Card",
    636: "Work permit",
    659: "Frontier Worker Permit",
    661: "Vaccination against: Covid 19",
    689: "Overseas Employment Certificate OEC",
    696: "Seafarers´Identity Document",
}

CERT_COMPETENCY = {
    1: "2nd Eng. on ships with power 3000 KWT or more (unlimited)",
    2: "2nd Eng. on ships with power less than 3000 KWT",
    3: "Rating part of Navigational Watch",
    4: "Ch. Eng. on ships with power 3000 KWT or more (unlimited)",
    5: "Ch. Eng. on ships with power less than 3000 KWT",
    6: "Chief mate on ships less than 3000 GT",
    7: "Chief mate on ships of 3000GT or more (unlimited)",
    9: "Eng. Officer on ships with power less than 750 Kw",
    10: "Eng. Officer on ships with power of 750 Kw or more",
    11: "GMDSS (General Operator)",
    13: "Master on ships less than 3000 GT",
    14: "Master on ships of 3000GT or more (unlimited)",
    16: "Rating part of Engineering watch",
    17: "Officer in charge of a navigation watch",
    25: "Ship`s Cook",
    155: "Master on ships below GT 500",
    160: "Officer in charge of an Engineering Watch",
    171: "Chief Mate - Local voyages below GT 500",
    172: "Master for Inland Waters",
    227: "Ch.Mate on ships of 500 gross tonnage or more",
    228: "Master on ships of 500 GT or more",
    638: "Able Seaman Deck II/5",
    640: "Able seaman engine III/5",
    649: "Electro-Technical Rating Sec. (ETR)",
    650: "Electro-Technical Officers (ETO)",
    651: "Officer in charge of a navigational watch on merchant ships up to 1600 GT",
    652: "Official Cadet Certificate",
    658: "Chief engineer of fishing vessels of less than 750 KW propultion power",
    663: "Officer in charge of an Engineering Watch on merchant ship up to 3000 KW",
    665: "Chief engineer of fishing vessels of less than 1400 KW propultion power",
    666: "Master on merchant ships less less than 1600 GT",
    667: "Ch. Eng. on ships with power less than 6000 KWT",
    668: "Chief engineer on Ships up to 10000 KW propulsion power",
    669: "Chief Mate or Officer in charge of an navigational watch on ships less than 1600 GT. Not allowed to command",
    671: "2nd Eng. on ships with power up to 6000 KWT propulsion power",
    672: "Seaman on fishing vessels",
    673: "Chief engineer on ships up to 1400 KW propulsion power",
    676: "2nd Eng. on ships up to 750 KWT propulsion power",
    683: "Welder",
    687: "Master on ships up to 6000 GT.",
    688: "THIRD CLASS REFRIGERATOR ENGINEER OFFICER",
    690: "MECANICO MAYOR NAVAL",
    693: "Officer in charge of a navigational watch on ships up to 3000 GT",
    694: "ANSCHÜTZ SYNAPSIS ECDIS",
}

CERT_ENDORSEMENTS = {
    27: "GMDSS Endorsement",
    28: "Tanker Endorsement (Chemical) Management",
    29: "Tanker Endorsement (Chemical) Operational",
    30: "Tanker Endorsement (Chemical) Support",
    31: "Tanker Endorsement (Gas) Management",
    32: "Tanker Endorsement (Gas) Operational",
    33: "Tanker Endorsement (Gas) Support",
    34: "Tanker Endorsement (Oil) Management",
    35: "Tanker Endorsement (Oil) Operational",
    36: "Tanker Endorsement (Oil) Support",
    143: "COC Endorsement",
    695: "Ship´s Cook MLC 2006",
}

CERT_MEDICAL = {
    37: "Blood Chemical Test",
    38: "Cholera Vaccination",
    39: "Drug and alchohol test",
    40: "Hepatitis test",
    41: "HIV test",
    42: "Physical Examination Certificate",
    43: "Vaccination against: Yellow Fever",
    189: "Vaccination against: Hepatitis A",
    191: "Vaccination against: Hepatitis B",
    192: "Vaccination against: Typhoid",
    193: "Vaccination against: Polio",
    194: "Vaccination against: Tetanus",
    195: "Vaccination against: Diphtheria",
    196: "Vaccination against: Cholera",
    197: "Vaccination against: Meningococcal",
    198: "Malaria visa (on-line training)",
    200: "Negative TB statement",
    233: "Seafarer Medical Certificate (ENG1)",
    655: "PCR -COVD TEST",
    657: "COVID-19 test",
    664: "Vaccination against: Measles",
}

CERT_TRAINING = {
    12: "GMDSS (Restricted Operator)",
    24: "Ship Security Officer",
    44: "Advanced Fire Fighting",
    46: "Advanced tanker training (Chemical)",
    47: "Advanced tanker training (Gas)",
    48: "Advanced tanker training (Oil)",
    49: "Basic Safety Training (SOLAS)",
    50: "Basic Safety Training (SOLAS) - Refresher Course",
    51: "Bridge Resources Management",
    52: "Bridge Team Management/Bridge Resources Management",
    53: "Cargo and Ballast Handling",
    54: "Competence updating course",
    55: "Corrosion Protection and Maintenance",
    56: "Crisis Management and Human Behavior",
    57: "Crowd management",
    58: "Crude Oil Washing",
    59: "Dangerous Cargo Handling",
    60: "Dynamic Positioning (Advanced) DPA",
    61: "Dynamic Positioning (Full) DPO Unlimited",
    62: "Dynamic Positioning (Induction) DPI",
    63: "Efficient Deck Hand (EDH)",
    64: "Efficient Engine Room Rating (EER)",
    65: "Medical First Aid",
    66: "Engine Room Resources Management",
    67: "Engine Room Simulator",
    68: "Engine Room Team Mangement",
    69: "Fast rescue boats",
    71: "HAZMAT",
    72: "Helicopter Underwater Egress Training (HUET)",
    73: "Ice Navigation",
    74: "Inert Gas System",
    75: "Large Vessels Handling",
    76: "Loading Control System",
    77: "Maritime English",
    78: "Medical Care on board Ship (Limited)",
    79: "Medical Care on board Ship (Unlimited)",
    80: "Navigation Bridge Teamwork (Management)",
    81: "Navigation Bridge Teamwork (Operational)",
    82: "Navigation Bridge Teamwork (Support)",
    83: "OLF/OPITO/NOGEPA",
    86: "Proficiency Survival Craft and Rescue Boat (other than Fast Rescue boats)",
    87: "Radar Navigation, Manual and Automatic Radar Plotting Aids (ARPA) Management",
    88: "Radar navigation, manual and automatic radar plotting aids (ARPA) Operational",
    89: "Radar navigation, manual and automatic radar plotting aids (ARPA) Support",
    91: "Safety Management System",
    92: "Search and rescue operations (Management)",
    93: "Search and rescue operations (Operational)",
    94: "Search and rescue operations (Support)",
    95: "Ship Handling Simulator",
    96: "Shore-based fire fighting",
    100: "Tanker Familiarization (Chemical)",
    101: "Tanker Familiarization (Gas)",
    102: "Tanker Familiarization (Oil)",
    103: "The Operational Use of Electronic Chart Display and Information Systems (ECDIS)",
    104: "Leadership and Teamwork (Management Level) IMO 1.39",
    138: "H2S/BA",
    144: "International Safety Management Code",
    145: "Radar Simulator",
    146: "ARPA Simulator",
    148: "Harbour Craft Master Course",
    149: "Oil Spill Control Course",
    154: "Proficiency in Fast Rescue Boat",
    158: "Oil Tanker Specialized Training Program",
    159: "Security Familiarization (ISPS Code)",
    162: "Ship Security Awareness",
    163: "Fitter General",
    164: "Electrical Installation",
    165: "Marine Accident Investigation",
    166: "Crane Operator",
    167: "Shielded Metal Arc Welding II",
    168: "Tanker Familiarization",
    169: "Liquified Gas Tanker Specialized Training Programme",
    170: "Chemical Tanker Specialised Training Programme",
    174: "Shipboard safety officer",
    186: "Navigation and Watch Keeping",
    202: "BOSIET",
    205: "Medical Care & Medical First Aid",
    206: "Radar Observation, Plotting and Automatic Radar Plotting Aids (ARPA)",
    208: "Norwegian Pilot Exemption",
    211: "Radar, ARPA, bridge team work and search and rescue",
    214: "Polution Prevention Duties",
    216: "Oil Tankers Operation & Maintenance of Inert Gas Systems",
    217: "Chemical Tankers Operation & Maintenance of Inert Gas System",
    218: "Oil Tankers Cargo & Ballast Handling",
    219: "Chemical Tankers Cargo & Ballast Handling",
    221: "Theoretical,Practical & Simulating training using AIS",
    222: "Ship personnel having specific duties on the program",
    224: "Dynamic Positioning (Full) DPO Limited",
    225: "High voltage equipment",
    226: "Maintenance of electrical and electronic equipment",
    231: "SDP maintenance course",
    234: "Oil Tanker Familiarisation (OTF)",
    236: "Elementary First Aid (EFA)",
    237: "Fire Prevention & Fire Fighting (FPFF)",
    238: "Personal Safety & Social Responsibilities (PSSR)",
    239: "Personal Survival Techniques (PST)",
    240: "STCW basic training",
    242: "Chemical Tanker Familiarization (CTF)",
    244: "Liquified Gas Tanker Familiarization (LGTF)",
    245: "RO-RO Passenger Ships Familiarization (Crowd & Crises Management) (PSF)",
    246: "Basic Safety Training and Instruction",
    247: "Carriage of Dangerous and Hazardous Substances",
    249: "Tanker Familiarization (Oil, Gas and Chemical Tankers)",
    394: "Security training for Seafarers with Designated Security Duties",
    637: "PASSENGER SHIPS (Reg.V/2 par 4,5,6 & 7; Sec.A-V/2, 2.1,2.2,2.3,2.4)",
    641: "Basic Training for Ships Subject to the IGF Code",
    642: "Advanced Training for Ships Subject to the IGF Code Reg. V/3.8, Sect. A-V/3.2",
    643: "Basic Electronics at sea",
    644: "TYPE SPECIFIC TRAINING IN Transas Navisailor 4000 ECDIS",
    645: "Formacion teórico-práctica para operadores de Carretillas Elevadoras y Plataformas Elevadoras",
    646: "ECDIS Specific Raytheon Anschütz",
    647: "Safety Training for Personnel Providing Direct Service to Passengers in Passenger Spaces",
    648: "Passenger Safety, Cargo Safety and Hull Integrity Training",
    653: "Leadership and Teamwork (Operational Level) IMO 1.39",
    654: "Company Security Officer",
    656: "Marine Enviromental Awareness",
    660: "SAR ON - SCENE COORDINATOR (IAMSAR Manual – Vol.III)",
    662: "ECDIS VisionMaster FT",
    670: "FURUNO ECDIS TYPE SPECIFIC TRAINING COURSE",
    674: "SIMRAD ECDIS training",
    675: "Marine Evacuation Systems Training (MES)",
    677: "JRC JAN-7201/7201S/9201/9201S",
    678: "PROFICIENCY IN SECURITY AWARENESS",
    682: "High Pressurised Pipe Welding",
    692: "Basic training for Oil & Chemical Tanker Cargo Operations",
}

CERT_MIGRATION = {
    256: "ABLE SEAMAN II/4",
    262: "AUXILIAR DE BUQUE DE PASAJE",
    263: "AVANZADO DE MANIOBRAS Y NAVEGACION",
    264: "BANKSMAN/SLIMGER",
    268: "BOSUN II/4",
    273: "BUQUES QUIMIQUEROS",
    274: "CALDERETERO",
    277: "CATERING COURSE",
    278: "CES SEAGULL 4.1.",
    283: "Company Policy/Alcohol and Drugs/Enviroment/Politica de Compañía/Alcohol y Drogas/Medio Ambiente",
    284: "Computer Familiarization Training (CFT)",
    285: "CONTRATO",
    288: "Criminal or police record",
    293: "DECK & ENGINE RATING",
    297: "DP FULL LIMITED",
    300: "DP MAINTENANCE",
    302: "ELECTRICAL & ELECTRONIC ENGINEERING",
    303: "ELECTRICAL ENGINEER III/6",
    304: "ELECTRICIAN",
    305: "ELECTRO-TECHNICAL RATING Sec. A-III/7",
    316: "FITTER/MOTORMAN",
    317: "FOOD HANDLING",
    319: "FULL MISSION SIMULATOR TRAINING-HOPPER DREDGER WITH RUDDER PROPELLER",
    320: "GALLEY BOY",
    321: "GENERAL PURPOSE",
    323: "H2S AWARENESS",
    325: "HIGH SPEED CRAFT",
    327: "HOISTING MATERIAL",
    328: "HOTEL STAF.",
    330: "IAS KONSBERG SYSTEM MAINTENANCE (TECHNICAL)",
    331: "IAS KONSBERG SYSTEM OPERATIONAL",
    332: "ILO Checklist - Pre-contract Check list for requirements of the MLC 2006",
    336: "Labour Prevention Risk",
    337: "LAUNCH OPERATOR COURSE",
    341: "MANAGEMENT OF CONFRONTATION",
    342: "MARINE EVACUATION SYSTEMS M.E.S.",
    343: "MARINE TECHNICIAN",
    352: "MES TRAINING",
    353: "MESSMAN",
    354: "NOGEPA (Basic Offshore SAfety Int. & Emergency Response Training incl. HUET plus Emergency Breathing",
    355: "Offshore Crane Operator Stage 1 Training",
    356: "Offshore Crane Operator Stage 2 Training",
    357: "Offshore Crane Operator Stage 3 Training",
    361: "OILER/MOTORMAN III/4",
    362: "OLF accepted upgrade to the Norwegian Continental staff",
    363: "OPERATION AND MAINTENANCE OF FRAMO CARGO PUMPING SYSTEM",
    364: "ORDINARY SEAMAN",
    367: "PATRON",
    368: "PATRON ALTURA",
    369: "PATRON DE CABOTAJE",
    370: "PATRON MAYOR DE CABOTAJE",
    371: "PATRON PESCA LITORAL",
    372: "PATRON PORTUARIO",
    375: "PRE-MEDICAL CERTIFICATE (Italy Flag)",
    379: "PUMPMAN",
    383: "RADIO OFFICER, 1ST CLASS",
    384: "RATING",
    385: "REEFER ENGINEER",
    386: "Risk Assessment & Incident Investiagion Familiarisation",
    388: "ROC IV/2 & ERC",
    391: "Seafarer Employment Agreement",
    395: "SERVICIO PREVENCION DE RIESGOS LABORALES",
    396: "SHIP HANDLING & NAVIGATION ADVANCED COURSE",
    397: "SHIP PEDESTAL CRANE",
    400: "SHIPFITTER",
    402: "SIGNAL MEN",
    403: "SKIPPER",
    404: "SKIPPER LIMITED, CLASS B",
    405: "SMS LNG MANOUVERING",
    406: "STEWARD",
    407: "TM MASTER/ TM MASTER",
    414: "WELDER",
    415: "WIPER",
    633: "Other",
    634: "NOGEPA (Basic Offshore SAfety Int. & Emergency Response Training incl. HUET plus Emergency Breathing System.",
    679: "APPRAISAL REPORT",
    680: "Form A, B, C",
    681: "Crew join clearance",
    684: "CV",
    685: "LATHE MACHINE COURSE",
    686: "SHIELDED METAL ARC WELDING",
}

# Map of certificate category name -> its lookup dict
CERT_CATEGORIES = {
    "Travel Documents": CERT_TRAVEL_DOCUMENTS,
    "Certificate of Competency": CERT_COMPETENCY,
    "Endorsements": CERT_ENDORSEMENTS,
    "Medical": CERT_MEDICAL,
    "Training": CERT_TRAINING,
    "Seafarer Migration Record": CERT_MIGRATION,
}

# ============================================================
# EXPERIENCE LOOKUPS
# ============================================================

VESSEL_TYPE_LOOKUP = {
    1: "Reefer",
    2: "Dry Cargo",
    3: "Ro-Ro",
    5: "Trawler",
    6: "Fishing",
    7: "Container",
    8: "CarCarrier",
    11: "Passenger",
    13: "General Cargo",
    14: "Seismograph",
    15: "Minesweeper",
    16: "Ice-breaker",
    17: "Salvor",
    18: "Chemical Tanker",
    19: "Oil Tanker",
    20: "OBO",
    22: "LPG",
    23: "Lifestock carrier",
    24: "Research/Survey Vessel",
    25: "Heavylift",
    26: "Dredger",
    28: "Lash",
    29: "Sailing",
    30: "Tug",
    31: "Tanker",
    32: "Other",
    33: "DSV",
    104: "Gas Tanker",
    105: "Lo-Ro",
    106: "Multipurpose",
    108: "Supply Vessel",
    110: "Barge",
    113: "AHTS",
    115: "Ferry",
    116: "Emergency Rescue (ERRV)",
    118: "Oil Tanker",
    120: "Ro-Pax",
    121: "Oil Platform",
    122: "Drilling Rig",
    123: "Bitumen Tanker",
    124: "Drillship",
    127: "FPSO",
    128: "Yacht",
    129: "Ro-Lo",
    130: "Seismic Support",
    131: "Fishing Protection (FPV)",
    132: "Cable layer",
    133: "Crane vessel",
    137: "FSIV DPI",
    138: "Vehicle Carrier",
    139: "Landing Craft",
    140: "Guard Vessel",
    141: "Cement Carrier",
    142: "Pipe Carier/Pipelay",
    145: "Jack-Up Barge",
    147: "Crew Boat",
    148: "Pilot Boat",
    149: "Mooring Boat",
    152: "Bulk carrier",
    153: "Cruise Ship",
    154: "Harbour Tug",
    158: "Well boat",
    159: "Split.Hopper barge",
    161: "Hydrographic",
    162: "Rock Carrier",
    163: "WFSV",
    164: "Fish Factory ship",
    165: "Stand by vessel",
    170: "AHT",
    172: "PSV",
    175: "DSV",
    177: "ASD",
    178: "OSV",
    180: "IBSV",
    181: "ROV",
    182: "SDW",
    183: "Shoalbuster",
    184: "SSDV",
    185: "OCV",
    186: "LNG",
    191: "MADERERO",
    200: "FAST FERRY",
    206: "FLOTEL",
    207: "ATS",
    210: "MAINTENANCE SUPPORT VESSEL",
    212: "VEGETABLE OIL TNK",
    213: "CHE/OIL PRODUCTS TANKER",
    214: "HIGH SPEED CRAFT",
    216: "Utility Vessel",
    217: "Pleasure Craft",
    218: "Patrol Vessel",
    219: "Pollution Control Vessel",
    220: "Motor Hopper",
    222: "Exhibition Ship",
    223: "SAR",
    224: "Buoy-Laying Vessel",
    225: "Hospital Ship",
    226: "Anti-Pollution",
    227: "nan",
    228: "Fruit Juice Refrigerated",
}

VESSEL_PUMP_LOOKUP = {
    23: "Centrifugal",
    24: "Framo",
    29: "Reciprocating Pump",
    30: "Screw pump",
    31: "Gear pump",
    32: "Piston pump",
    33: "Ram type pump",
    34: "Vane pump",
    35: "Centrifugal pumps",
    36: "Axial flow pumps",
    37: "Submersible pump",
    38: "Centrifugal-axial (mixed) pump",
}

VESSEL_GEAR_LOOKUP = {
    25: "2 Cranes",
    26: "3 Cranes",
    27: "4 Cranes",
    28: "Gearless",
    39: "lifting gear",
    40: "conveyor belt",
    41: "elevator",
    42: "derrick",
    43: "fork lift truck",
    44: "mobile crane",
    45: "straddle carrier",
    46: "tractor",
    47: "front/side loader",
    48: "van carrier",
    49: "dockside crane",
    50: "quay crane",
    51: "container crane",
    52: "gantry crane",
    53: "deck crane",
}

ENGINE_TYPE_LOOKUP = {
    1: "Diesel",
    2: "B&W",
    3: "MAN",
    4: "MAK",
    5: "Wartsila",
    6: "Sulzer",
    7: "Mitsubishi",
    8: "Pilstick",
    9: "Steam Turbine",
    10: "Deutz",
    11: "Other",
    12: "Akasaka",
    14: "6NVD",
    15: "FIAT",
    16: "KOBE DIESEL",
    17: "CATERPILLER",
    18: "YANMAR",
    19: "VOLVO",
    20: "SKODA",
    21: "RUSTON",
    22: "SKL",
    23: "STORK",
    24: "POTAR",
    25: "RD",
    26: "Nohab - Polar",
    27: "GMT",
    28: "Wichmann",
    29: "Frichs",
    30: "Hyundai",
    34: "Hanshin",
    37: "MIRRLEES BLACKSTONE",
    39: "Cummins",
    41: "8NVD",
    42: "Ulstein Aquamaster",
    43: "BERGEN",
    46: "Ulstein Bergen",
    48: "Industrie",
    51: "DC Electro Motor",
    53: "ABC",
    54: "MAN-B&W",
    55: "Niigata",
    56: "MDDCF-5935846",
    57: "KTA 50 M2 (HX)",
    58: "NIIGATA-6MG28HX",
    59: "CAT-3306",
    60: "D12D-C MH",
    61: "CAT-3412E",
    62: "KTA 19-M4",
    63: "C 32",
    64: "MWM",
    65: "BW-ALPHA",
    66: "Blackstone",
    67: "Alpha",
    68: "BOLNES",
    69: "Callesen",
    70: "Grenaa Diesel",
    71: "Daihatsu",
    74: "Rolls-Royce",
    75: "CAT 3516",
    77: "EMD",
    78: "CAT 360",
    79: "CAT",
    80: "MACH",
    81: "KUMERA",
    82: "WAUKESHA",
    83: "NINGBO DIESE",
    84: "Schottel",
    85: "ZIBO DIESEL ENGINE",
}

DP_TYPE_LOOKUP = {
    1: "DP Class 0",
    2: "DP Class 1",
    3: "DP Class 2",
    4: "DP Class 3",
}

DP_MANUFACTURER_LOOKUP = {
    5: "Autonav",
    6: "Comex",
    7: "Converteam",
    8: "DCNS",
    9: "Deep Down Marine Technologies",
    10: "EMI",
    11: "iMAR Navigation",
    12: "Kongsberg Maritime",
    13: "L3",
    14: "Mitsui Engineering",
    15: "NAUDEQ",
    16: "Nautronix",
    17: "Navis Engineering",
    18: "Norr Systems",
    19: "Praxis Automation Technology",
    20: "QPS Quality Positioning Services",
    21: "Rolls-Royce",
    22: "SIREHNA",
}

EXP_RANK_LOOKUP = {
    1: "MASTER",
    2: "COFF",
    5: "4OFF",
    10: "OS",
    11: "DCAD",
    12: "CENG",
    13: "2ENG",
    14: "3ENG",
    17: "ETO",
    19: "FITTER",
    20: "MMAN",
    21: "ECAD",
    22: "COOK",
    23: "STW",
    24: "WELDER",
    25: "OILER",
    26: "WIPER",
    28: "MESSM",
    29: "Other",
    30: "MSI",
    39: "GP",
    41: "ELEC",
    50: "FRMAN",
    51: "2OFF",
    52: "3OFF",
    53: "4ENG",
    54: "1ENG",
    58: "MECH",
    59: "AB",
    60: "JENG",
    67: "PMAN",
    68: "ENG",
    69: "CHCOOK",
    72: "JOFF",
    75: "BOSUN",
    125: "MIGRATION-CHIEF ENGINEER BULK",
    133: "CE(MANT)",
    162: "MIGRATION-ARTISTA",
    166: "MIGRATION-OFF. STWD",
    176: "MIGRATION-SKIPPER",
    177: "MIGRATION-MECAMAR",
    178: "MIGRATION-RECEPTION SUP",
    232: "MIGRATION-POTMAN",
    240: "LIMPIADOR",
    241: "MIGRATION-PATRON PORTUARIO",
    292: "MIGRATION- RSA",
    314: "MIGRATION-AB/CR",
    319: "MIGRATION-C/O/SDPO",
    321: "MIGRATION-2/O/JDPO",
    327: "MIGRATION-ENGINE CLEANER",
    500: "1AEA",
    501: "2/O/DPO",
    502: "2COOK",
    503: "1AE",
    504: "2AE",
    505: "3AE",
    506: "2OFS",
    507: "ABCOOK",
    508: "ANI",
    509: "APOF",
    510: "AS/D",
    511: "APE",
    512: "APB",
    513: "APAX",
    514: "AHOST",
    515: "ACOOK",
    516: "ACABIN",
    517: "B.UT",
    518: "B/WTR",
    519: "BBOY",
    520: "B.OP",
    521: "BARM",
    522: "BTND",
    523: "BWSS",
    524: "BSUP",
    525: "BTOP",
    526: "BSNA",
    527: "BSNB",
    528: "BSNC",
    529: "BSND",
    530: "BSNE",
    531: "BTCHR",
    532: "COSD",
    533: "CBOY",
    534: "CGIRL",
    535: "CSTWD",
    536: "CUTI",
    537: "CSER",
    538: "CALD",
    539: "CALDN",
    540: "CGEN",
    541: "CRPT",
    542: "CASH",
    543: "CASD",
    544: "CASM",
    545: "C.STOR",
    546: "CATR",
    547: "CSPV",
    548: "CLED",
    549: "ALIMP",
    550: "CENGT",
    551: "CE/1AE",
    552: "COFFE",
    553: "C.STWD",
    554: "2C.STWD",
    555: "ACSTWD",
    558: "S.CLNR",
    562: "R.COOK",
    563: "COOK/ST",
    564: "CRNO",
    565: "DMAN",
    566: "DWMAN",
    567: "DBOY",
    569: "DECK FITTER",
    572: "DHND",
    575: "DJ",
    576: "DR",
    577: "DNK",
    587: "S.ETO",
    590: "F/MTM",
    591: "F/W",
    592: "FMAN",
    593: "FOODM",
    594: "FORKD",
    595: "G/BOY",
    596: "G. UTI",
    597: "G.ENG",
    598: "G.MEC",
    599: "GVNS",
    600: "GRS",
    601: "GUARDIAN",
    602: "GUIT",
    603: "HMAN",
    604: "H.BART",
    605: "H.CLE",
    606: "H.REC",
    608: "H.WAIT",
    609: "HKCL",
    611: "HTSS",
    612: "AHTSS",
    613: "H.MAN",
    614: "H.S.ENG",
    616: "H.UT",
    617: "ILU",
    618: "J.CMA",
    619: "JWRL",
    620: "A.PURS",
    621: "J.ETO",
    622: "K.UTI",
    623: "A.GALLEY",
    624: "LUNDRY",
    625: "LBSN",
    626: "LMTM",
    628: "LKEE",
    629: "MAG",
    630: "MTR",
    633: "AB/MTM",
    634: "MSSG",
    635: "M.BLK",
    636: "M.TNK",
    637: "M-CO",
    638: "M-SDPO",
    639: "MN2",
    640: "MNM",
    642: "MMN",
    643: "MN1",
    644: "MED.O",
    645: "2AMES",
    646: "AMESS",
    648: "MUSIC",
    649: "N.COOK",
    650: "N.STWD",
    651: "N.UTI",
    652: "NURSE",
    654: "O.MESS",
    656: "MTM/ETO",
    657: "PTR",
    658: "PANG",
    660: "BKR",
    661: "PATMAN",
    662: "SKPR",
    664: "PIAN",
    665: "PILT",
    666: "PLUM",
    667: "P.MST",
    669: "PPRR",
    670: "PSR",
    671: "J.RAD",
    672: "S.RAD",
    673: "RECEPT",
    675: "REDER",
    676: "A. REEFER",
    677: "ENG REEF",
    678: "RPMAN",
    680: "RIGME",
    681: "RIG",
    682: "RNECK",
    683: "RTBT",
    684: "S.OFF",
    685: "2MEC",
    686: "2PLUMB",
    687: "2STWD",
    688: "SECR",
    689: "SER.U",
    690: "SBSN",
    691: "S ELECT",
    692: "SFITT",
    694: "SSO",
    695: "SHIP.FIT",
    696: "ASHOP",
    697: "SHOPG",
    699: "SBFTT",
    700: "SCARG",
    701: "S.RECEPT",
    702: "A.STWD",
    703: "A.STORE",
    704: "S.STORE",
    705: "STOREM",
    706: "SCARG/SUPERN",
    707: "S.INTENT",
    708: "SUPERN",
    710: "S.CAT",
    711: "S.HOST",
    712: "S.LIMP",
    713: "S.RECEPT",
    714: "CLNTNK",
    715: "T. ENG",
    716: "TUTOR",
    717: "U.MTM",
    718: "U.MAN",
    719: "WTR",
    720: "YMAN",
    721: "ABOSN",
    722: "AB II/5",
    723: "CLNR",
    724: "RP.REST",
    725: "RP.COOK",
    726: "CASD S.",
    727: "ETR",
    729: "Cust.Serv.Crew",
    730: "INSP",
    731: "MST/1OFF",
    732: "OBS Spv.",
    733: "D.MAN",
    734: "ABJUN",
    735: "ENG FITTER",
    736: "SOUS CHEF",
}

OFF_REASON_LOOKUP = {
    1: "end of contract",
    2: "disciplinary",
    3: "illness",
    4: "injury",
    5: "incomptence",
    6: "death",
    7: "transfer",
    9: "own request",
    10: "family matters",
    11: "rank change",
    12: "promotion",
    13: "end of trial period",
    14: "Ship renamed",
}
